### ISSUE TITLE
Consider adding Open Cultuur Data API

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/garmonbozia#33]
Hi,

Opencultuurdata.nl collects openly licensed cultural heritage works (similar to Europeana). 

It harmonises APIs from several Dutch heritage institutions. See http://docs.opencultuurdata.nl/ for more details

**Comment by robmyers** [comment]
Is this a strict subset of Europeana?

This also raises the question of whether we want to explicitly support geographic search (by continent/nation/region/town), and by form (comic book/sculpture/machinima rather than image).

Also how to prioritize e.g. single institution collection APIs vs. platform APIs.

**Comment by mzeinstra** [comment]
No, however it can produce the same results but it is not connected to Europeana. See http://search.opencultuurdata.nl/#/ for some examples.

I don't know how you need/should deal with the multitude of sites out there that have CC material.

**Comment by robmyers** [comment]
So (just to be clear) - it has material that isn't in /won't be in Europeana?
