### ISSUE TITLE
separate results per platform

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/garmonbozia#36]
results are not separated in their source platform

**Comment by robmyers** [comment]
They are ordered by platform as a result of the way we query platform APIs, but are not visibly grouped under the platform name.

This raises a design question.

The conceptual model for search engines at the moment is Google, which gives an ungrouped, unlabelled (by source) list (or grid) of results ordered by relevance.

Do we pursue this model in order to give people a familiar experience? If so should we randomize the order of calling platform search APIs or use some other method of making ordering "fair" over time. I don't think we have the information from platforms to rank the results.

Or do we break the results into groups under the platform name as a title? This has the advantage of helping people to find results from platforms they favour. But we will eventually be searching many different sources in some cases (e.g. OER), and we are meant to be searching "the commons", so having (e.g.) 20 different headers and sections may frustrate users, especially those with limited screen real estate on mobile platforms.

**Comment by mzeinstra** [comment]
You can host both views? You might even allow cookies that set preferable places to search. 

Also you might allow per platform paging, getting new result from a platform where you like the search results best

Also you might allow a link that allows native searching on the platforms. As said before I think this should be a server by the commons as well and you should promote the platforms that make this possible whenever you can.

BTW I did ask for your design specs: https://github.com/creativecommons/garmonbozia/issues/32 but I believe I had a scrap with Matt about how to voice feedback.
