### ISSUE TITLE
Provide information about source platforms

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/garmonbozia#38]
I want to be able to see which platforms are used and why and how I can apply my platform in a way understandable for non-developers.

**Comment by robmyers** [comment]
Yes that sounds good.

Listing platforms would be very useful for encouraging users to see the platform as comprehensive, and for encouraging platforms to contribute search modules (I assume that is what you mean by "apply your platform"). We can require search modules to require that information. And yes we should make this information accessible to everyone to help encourage them to bring it to the people who can make it happen technically.

"Why" will always be "because they host Creative Commons-licenced work". We want this to ultimately be a search engine for the whole commons.

**Comment by mzeinstra** [comment]
Yes, 

But I would also like to see that this becomes a search engine by the commons as well. It would be good  to promote those platforms you are wrapping into this service. That would benefit the commons most I believe.

**Comment by robmyers** [comment]
I agree that we want to encourage people to use services that support/are in the commons, and I can see how name recognition is part of that. The question is how high up in the interface to mention individual sources in the UI, as this has a cost in screen real estate and as I say we are hoping to support many services. At present I was imagining this would go on the individual result page but if it adds value in the search results page we should definitely look at that, it's easy enough technically to simply name services (although using logos has compliance overhead and may be distracting).

**Comment by robmyers** [comment]
We need a strategy for this, and also to work it into the Search Provider API.
