### ISSUE TITLE
check Rijksmuseum API and add to search (if open enough)

### ISSUE THREAD

**Issue by RCEurope1** [creativecommons/garmonbozia#4]
people from the  Rijksmuseum in Amsterdam told John that there's an API through which the digitized PD works (that are otherwise available only after registering with RijksStudio or other webservices of the museum) can be downloaded w/o registration; Ryan suggested to check that and add it as a source to search.creativecommons.org if possible

**Comment by mzeinstra** [comment]
You need a key for this service, see: https://www.rijksmuseum.nl/en/api Otherwise it works really well. Here is a python implementation that harvest that API: https://github.com/openstate/open-cultuur-data/blob/59af74f2fcb97b53f250518f46882d8ec7613ec3/ocd_backend/extractors/rijksmuseum.py

@lizzyjongma should be able to help you with any further issues. (probably best to reach her at https://twitter.com/lizzyjongma )
